Description: A simple VPC demo



Parameters:

  VPCCIDR:
    Type: String
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16

  MyPrivateSubnetCIDR:
    Type: String
    Description: CIDR block for private subnet
    Default: 10.0.1.0/16
  MyPublicSubnetCIDR:
    Type: String
    Description: CIDR block for the public subnet
    Default: 10.0.2.0/16

  EnvironmentName:
    Type: String
    Default: prod
    Description: Environment name to use as prefix for resource names and tags.

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}-demo-vpc


  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Network
          Value: my-igw
      Tags:
      - Key: Name
        Value: my-private-subnet
      - Key: Network
        Value: Private

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref MyInternetGateway
      VpcId: !Ref MyVPC

  MyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        !Select [ '0', !GetAZs "" ]
      CidrBlock: !Ref MyPublicSubnetCIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName}-public-subnet
      VpcId: !Ref MyVPC



  
Outputs:


  
  VPCCIDR:
    Description: VPC CIDR
    Value: !Ref VPCCIDR

  VPCID:
    Description: VPC ID
    Value: !Ref MyVPC
