Description:  This template deploys a simple VPC.

Parameters:

  VpcCIDR1:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.10.0.0/16

  VpcCIDR2:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.11.0.0/16

    
  Subnet1CIDR:
    Type: String
    Default: 10.11.5.0/16


Resources:
  MyVPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR1
      Tags:
        - Key: Name
          Value: vpcA
        - Key: Project
          Value: ProjectX

  MyVPC2:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR2
      Tags:
        - Key: Name
          Value: vpcB
        - Key: Project
          Value: ProjectX


  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC2
      CidrBlock: !Ref Subnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: subnet1

Outputs:
  VpcOut:
    Description: A reference to MyVPC2
    Value: !Ref MyVPC2

  Subnet1Out:
    Description: A reference to the subnet 
    Value: !Ref Subnet1
    Export: Subnet1Export